version: "3"
services:
  redis:
    image: redis:6-alpine
    container_name: redis
    network_mode: host
    command: >
      --requirepass nromanen
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","-a","nromanen","ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  mysql:
    image: mariadb:10.6
    container_name: mysql
    network_mode: host
    environment:
      - MARIADB_USER=nromanen
      - MARIADB_PASSWORD=nromanen
      - MARIADB_DATABASE=manager
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin status"]
      interval: 1s
      timeout: 3s
      retries: 30
